version: '2'

volumes:
    database_data:
        driver: local

services:
    apache:
        image: httpd:latest
        ports:
            - '8080:80'
        volumes:
            - ./docker/apache2/htdocs:/usr/local/apache2/htdocs/
        volumes_from:
            - php
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: 
            MYSQL_USER: 
            MYSQL_PASSWORD:
